# ~/.config/starship.toml

add_newline = false

format = """\
  $time\
  $hostname\
  $memory_usage\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $cmd_duration\
  $custom\
  $line_break\
  $jobs\
  $battery\
  $conda\
  $character\
  """
#

[hostname]
format = "on [$hostname]($style) "

[nodejs]
disabled = true

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[battery.display]
threshold = 30
style = "bold red"

[character]
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style) "

[directory]
truncation_length = 2
format = "in [$path]($style)[$lock_symbol]($lock_style) "

[line_break]
disabled = true

[memory_usage]
disabled=false
threshold=20
format = "with [${ram}]($style) "

[time]
disabled = false
format = "🧬 [$time]($style) "
